### ISSUE TITLE
Python wheel doesn't install CMake config files

### ISSUE THREAD

**Issue by mofeing** [QE-Lab/dqcsim#671]
When `dqcsim` is installed via `pip`, the CMake config files are not installed (`dqcsimConfig.cmake`, `dqcsimConfigVersion.cmake`). This is expected as `setup.py` has not yet been updated. The easy part is to update this part:

https://github.com/QE-Lab/dqcsim/blob/c0e596ee56e67f6caa067e97e1085a86974b8177/setup.py#L187-L189

The somewhat more complicated thing is that when building the wheel, it would need to call CMake to generate the two CMake config files. Good thing is that it just needs to call CMake for configuration step, not building neither installation.

The command
```
cmake -B build .
```
would generate `build/dqcsimConfig.cmake` and `build/dqcsimConfigVersion.cmake`.

I just don't know how to this packaging step and I guess it would be part of your automated deployment.

**Comment by mbrobbel** [comment]
Fixed in #672. I'll publish a new release. Thanks again for the improvements and suggestions.

**Comment by mofeing** [comment]
Thanks to you for the hard work. Sorry for opening more issues 😅 

I've just noticed that CMake is not capable to find the config modules if installed through the `pip` since the install prefix won't be the usual `/usr/local`. I think I can fix this. I will upload a PR later.

**Comment by mbrobbel** [comment]
Ok thanks! I will fix the broken manylinux wheel build and publish a new release.
